
package co.edu.eam.servicesCompra;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CompraController", targetNamespace = "http://co.edu.eam.ingsoft.distribuidos")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CompraController {


    /**
     * 
     * @param idCliente
     * @param valorTotal
     * @param itemsCompra
     * @return
     *     returns boolean
     */
    @WebMethod(action = "crearCompra")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "operacionCrearCompra", targetNamespace = "http://co.edu.eam.ingsoft.distribuidos", className = "distribuidos.ingsoft.eam.edu.co.OperacionCrearCompra")
    @ResponseWrapper(localName = "operacionCrearCompraResponse", targetNamespace = "http://co.edu.eam.ingsoft.distribuidos", className = "distribuidos.ingsoft.eam.edu.co.OperacionCrearCompraResponse")
    public boolean operacionCrearCompra(
        @WebParam(name = "id_Cliente", targetNamespace = "")
        int idCliente,
        @WebParam(name = "valor_total", targetNamespace = "")
        double valorTotal,
        @WebParam(name = "items_compra", targetNamespace = "")
        List<ItemsDTO> itemsCompra);

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "generaId", targetNamespace = "http://co.edu.eam.ingsoft.distribuidos", className = "distribuidos.ingsoft.eam.edu.co.GeneraId")
    @ResponseWrapper(localName = "generaIdResponse", targetNamespace = "http://co.edu.eam.ingsoft.distribuidos", className = "distribuidos.ingsoft.eam.edu.co.GeneraIdResponse")
    public int generaId();

}
