
package co.edu.eam.servicesCliente;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ClienteController", targetNamespace = "http://co.edu.eam.ingsoft.distribuidos")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ClienteController {


    /**
     * 
     * @param cliente
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "crearCliente")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "operacionCrear", targetNamespace = "http://co.edu.eam.ingsoft.distribuidos", className = "distribuidos.ingsoft.eam.edu.co.OperacionCrear")
    @ResponseWrapper(localName = "operacionCrearResponse", targetNamespace = "http://co.edu.eam.ingsoft.distribuidos", className = "distribuidos.ingsoft.eam.edu.co.OperacionCrearResponse")
    public String operacionCrear(
        @WebParam(name = "cliente", targetNamespace = "")
        Cliente cliente);

    /**
     * 
     * @param cedula
     * @return
     *     returns distribuidos.ingsoft.eam.edu.co.Cliente
     */
    @WebMethod(action = "buscarCliente")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "operacionBuscar", targetNamespace = "http://co.edu.eam.ingsoft.distribuidos", className = "distribuidos.ingsoft.eam.edu.co.OperacionBuscar")
    @ResponseWrapper(localName = "operacionBuscarResponse", targetNamespace = "http://co.edu.eam.ingsoft.distribuidos", className = "distribuidos.ingsoft.eam.edu.co.OperacionBuscarResponse")
    public Cliente operacionBuscar(
        @WebParam(name = "cedula", targetNamespace = "")
        String cedula);

}
