
package co.edu.eam.servicesCliente;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.8
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ClienteControllerService", targetNamespace = "http://co.edu.eam.ingsoft.distribuidos", wsdlLocation = "http://localhost:8089/servicio_soap/ClienteController?wsdl")
public class ClienteControllerService
    extends Service
{

    private final static URL CLIENTECONTROLLERSERVICE_WSDL_LOCATION;
    private final static WebServiceException CLIENTECONTROLLERSERVICE_EXCEPTION;
    private final static QName CLIENTECONTROLLERSERVICE_QNAME = new QName("http://co.edu.eam.ingsoft.distribuidos", "ClienteControllerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8089/servicio_soap/ClienteController?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CLIENTECONTROLLERSERVICE_WSDL_LOCATION = url;
        CLIENTECONTROLLERSERVICE_EXCEPTION = e;
    }

    public ClienteControllerService() {
        super(__getWsdlLocation(), CLIENTECONTROLLERSERVICE_QNAME);
    }

    public ClienteControllerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CLIENTECONTROLLERSERVICE_QNAME, features);
    }

    public ClienteControllerService(URL wsdlLocation) {
        super(wsdlLocation, CLIENTECONTROLLERSERVICE_QNAME);
    }

    public ClienteControllerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CLIENTECONTROLLERSERVICE_QNAME, features);
    }

    public ClienteControllerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ClienteControllerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ClienteController
     */
    @WebEndpoint(name = "ClienteControlPort")
    public ClienteController getClienteControlPort() {
        return super.getPort(new QName("http://co.edu.eam.ingsoft.distribuidos", "ClienteControlPort"), ClienteController.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ClienteController
     */
    @WebEndpoint(name = "ClienteControlPort")
    public ClienteController getClienteControlPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://co.edu.eam.ingsoft.distribuidos", "ClienteControlPort"), ClienteController.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CLIENTECONTROLLERSERVICE_EXCEPTION!= null) {
            throw CLIENTECONTROLLERSERVICE_EXCEPTION;
        }
        return CLIENTECONTROLLERSERVICE_WSDL_LOCATION;
    }

}
